language: rust
rust:
- stable
os: osx
script:
- cargo build --verbose --release
- zip -r mac.zip target/release
deploy:
  provider: releases
  api_key:
    secure: r4enbvydJinkRDwgeYD2YJhl6bDR3QSd/NzJ/y9uO8iiqTj941cn2nUpxt76ictf3I9HNQdRG9P5A/Rw0iJPxFvd9JyzcH/PJIGxnuDP4Lm/GEEHuZsA4FS9bg8tMtx0+2P9au+X1TdG61AejViuzFFD7isQu61Ml8wZn8nT3QXqgn0JhwRy2knP6belz6snfkdzzKDdIuGGXY2YaHKkXrrX9umpB/Wk2oYCzxqJ0z3N5yJox7bScyF3BcOO5JYfJTApbjdJpikrlFvOkxRfVkX9w4Na9REDYlEq21UYBjfyK7pvwvlldvdqKgEQi7+5zuS8GvYLvMaKeYy7v3nlCr4KTFyPJy/KqLCu0kXHibopeEX9OouC5FbtxFHEgewP0xPXvo+heKvuDH56LVhCG+fdP1D2p2s5u96KyAoI1ezzuba+x/MQpVOoG2TfDmo/cB/1TRbXUrDyMwzjvGaMTlZg7meZNl9ax82FLGU9JMKIfbmWh2ux8zHxgZXLiTOaOWzKjingXbzzVsBRQDKXoE7sUAM37CgeIVimhx8m0HAkZOv/NIs2ifJ7HROKGt27k1A/7Quqavldm5Ak3fqtzLGV/XfGfdbq8fZGyGw8jbxlghLfvd1o4EjGwqpYwMaxUP9xhjDqZKfYQyF6cLEVajgW2iowSiPvS8KCFgmXleE=
  file: mac.zip
  on:
    tags: true
